name: "ComputeGH"
on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: ComputeCS.sln
  DIST_PATH: dist
  BUILD_CONFIGURATION: Release
  YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
  YAK_EXE: yak.exe
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Get Yak
        run: curl -fSLo ${{env.YAK_EXE}} https://files.mcneel.com/yak/tools/latest/yak.exe && .\${{env.YAK_EXE}} version

      - name: Build .dll & .gha
        run: msbuild  /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Build Package
        run: cd ${{env.DIST_PATH}}\ && ..\${{env.YAK_EXE}} build

      - name: Push Package
        run: cd ${{env.DIST_PATH}}\ && Get-ChildItem . -Filter *.yak | ForEach-Object -Process {..\${{env.YAK_EXE}} push $_}

      - name: Prepare Release
        run: |
          Get-ChildItem dist -Filter *.yak | ForEach-Object -Process {$_[0] -match "[0-9.]+"}
          $version = $Matches[0]
          echo RELEASE_VERSION=$version | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSION }}
          body: |
            # Procedural Grasshopper plugin.
            Please find a working example by going to our [demo](https://github.com/procedural-build/demos) repo.

            ## Components Updated in this Release
            The following components have been updated since our last release and it is advised to replace them in any canvas you have.
            Just because the components have been updated, that doesn't mean that the only ones won't work any more, but there might be issues with added/removed/changed input, outputs, descriptions and tooltips.

            ## Installation

            We provide the option to install the Procedural Grasshopper plugin through the YAK package manager. 
            To install with YAK, just download and open the [ComputeVWT-DEMO.gh](https://github.com/procedural-build/demos/blob/master/VWT/ComputeVWT-DEMO.gh?raw=true) file and click install when the package manager opens.
            We also have a [video](https://www.youtube.com/embed/oQU_Uke5368) walking through the process 

            ## Update with YAK

            1. Write `TestPackageManager` in the Rhino console. 
            2. Select the `Installed` tab. 
            3. Click on `ProceduralCS`. 
            4. Click `Update`. 
            5. Restart Rhino

             ![alt text](https://github.com/procedural-build/ProceduralCS/raw/master/.github/releases/UpdateYAK.gif "Update ProceduralCS with YAK")

            ### Manual Installation/Update (Not recommended)
            If using the YAK package manager doesn't work you can install the package manually by downloading the [ComputeGH.gha](https://github.com/procedural-build/ProceduralCS/blob/${{env.RELEASE_VERSION}}/dist/ComputeGH.gha?raw=true) and [ComputeCS.dll](https://github.com/procedural-build/ProceduralCS/blob/${{env.RELEASE_VERSION}}/dist/ComputeCS.dll?raw=true) putting them in the Grasshopper Components folder.
             That folder can be found in Edit > Special Folders > Components.

             ![alt text](https://github.com/procedural-build/ProceduralCS/raw/master/.github/releases/GrasshopperLibraries.png "Find the Grasshopper Components folder.")

             **Remember to unblock ProceduralCS.dll and ProceduralGH.gha**

             ![alt text](https://github.com/procedural-build/ProceduralCS/raw/master/.github/releases/Unblock.png "Unblock ProceduralCS.dll and ProceduralGH.gha")

            This release is only working with Rhino 6!

          draft: false
          prerelease: false