name: "ComputeGH"
on: 
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: ComputeCS.sln
  DIST_PATH: dist
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet packages
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build .dll & .gha
        run: msbuild  /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Get Yak
        run: curl -fSLo yak.exe https://files.mcneel.com/yak/tools/latest/yak.exe && .\yak.exe version
        
      - name: Build Package
        working-directory: ${{env.GITHUB_WORKSPACE}}\${{env.DIST_PATH}}
        run: ..\yak.exe build
      
      - name: Push Package
        run: Get-ChildItem ${{env.DIST_PATH}}\ -Filter *.yak | ForEach-Object -Process {.\yak.exe push  $_}
