name: "ComputeGH"
on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: ComputeCS.sln
  DIST_PATH: dist
  BUILD_CONFIGURATION: Release
  YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
  YAK_EXE: yak.exe
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Get Yak
        run: curl -fSLo ${{env.YAK_EXE}} https://files.mcneel.com/yak/tools/latest/yak.exe && .\${{env.YAK_EXE}} version

      - name: Build .dll & .gha
        run: msbuild  /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Build Package
        run: cd ${{env.DIST_PATH}}\ && ..\${{env.YAK_EXE}} build

      - name: Push Package
        run: cd ${{env.DIST_PATH}}\ && Get-ChildItem . -Filter *.yak | ForEach-Object -Process {..\${{env.YAK_EXE}} push $_}

      - name: Prepare Release
        run: |
          Get-ChildItem dist -Filter *.yak | ForEach-Object -Process {$_[0] -match "[0-9.]+"}
          $version = $Matches[0]
          echo $version | Out-File -FilePath $env:RELEASE_VERSION -Encoding utf8 -Append
          $text = Get-Content .github\releases\release.md
          $Body = $text.Replace("{{RELEASE_VERSION}}" , $version)
          echo $Body | Out-File -FilePath $env:RELEASE_BODY -Encoding utf8 -Append

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSOIN }}
          body: ${{ env.RELEASE_TEXT }}
          draft: true
          prerelease: false